language: cpp
os: osx
compiler: g++

before_install:
    - brew install wget tar
    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-macosx.tar.gz
    - tar -xf premake-5.0.0-alpha7-macosx.tar.gz

script:
    - premake5 gmake
    - cd build
    - make config=debug unit-test
    - ./unit-test/bin/debug/unit-test
