language: cpp
os: osx
compiler: clang

before_install:
    - brew install wget
    - brew install glfw3
    - brew install glew
    - brew install glm
    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-macosx.tar.gz
    - tar -xf premake-5.0.0-alpha7-macosx.tar.gz

script:
    - ./premake5 gmake
    - cd build
    - cd 3rd
    - make
    - cd ..
    - make config=debug openswf
    - cd test
    - make
    - cd ../../bin
    - ./01-unit-test
