language: cpp
compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    
    - apt-key adv --keyserver keys.gnupg.net --recv-keys FFBA9E40
    - echo 'deb http://repo.nofla.me/ jessie main' >> /etc/apt/sources.list
    - apt-get update
    - apt-get install premake5

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"

script:
    - premake5 gmake
    - cd build
    - make config=debug unit-test
    - ./unit-test/bin/debug/unit-test
