language: cpp
os: osx
compiler: clang

before_install:
    - brew install wget
    - brew install glfw3
    - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-macosx.tar.gz
    - tar -xf premake-5.0.0-alpha7-macosx.tar.gz

script:
    - ./premake5 gmake
    - cd build
    - cd 3rd
    - make
    - cd ../openswf
    - make config=debug openswf
    - cd ../test
    - make
    - cd ..
    - ./test/bin/debug/01-unit-test
